### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by marc-poncet** [Commvault/terraform-provider-commvault#11]
Hello, I tried to test terraform by following the link bellow:
https://documentation.commvault.com/v11/essential/129245_run_test_configuration_for_commvault_terraform_module.html

**My configuration:**
Commvault 11.28.19
Terraform 1.3.6
GO 1.19.4

**Error:**
 Error: Plugin did not respond
│
│   with provider["registry.terraform.io/commvault/commvault"],
│   on main.tf line 15, in provider "commvault":
│   15: provider "commvault" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-commvault_v1.2.1.exe plugin:

panic: status: 407, body:

goroutine 50 [running]:
terraform-provider-commvault/commvault/handler.LoginWithProviderCredentials({0x13d0c078, 0x17}, {0x13d0c060, 0x18})
        terraform-provider-commvault/commvault/handler/LoginHandler.go:36 +0x24e
terraform-provider-commvault/commvault.providerConfigure(0x13d1e080)
        terraform-provider-commvault/commvault/provider.go:103 +0x2f2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0x1387b900, 0x13d0e1c8)
        github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/provider.go:275 +0xec
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0x13b6c350, {0x1838eac, 0x13d0e0a8}, 0x13d000a0)
        github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/helper/plugin/grpc_provider.go:487 +0x24d
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler({0x16ae700, 0x13b6c350}, {0x1838eac, 0x13d0e0a8}, 0x13d10090, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/tfplugin5/tfplugin5.pb.go:3251 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x13802e10, {0x1845734, 0x138a2100}, 0x13d20000, 0x13b7c5b8, 0x1c82f7c, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0xddd
google.golang.org/grpc.(*Server).handleStream(0x13802e10, {0x1845734, 0x138a2100}, 0x13d20000, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xa37
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x13896570, 0x13802e10, {0x1845734, 0x138a2100}, 0x13d20000)
        google.golang.org/grpc@v1.27.1/server.go:722 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0x7f

Error: The terraform-provider-commvault_v1.2.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Thx and Bye

Marco

**Comment by cvltmaheshp** [comment]
@marc-poncet - seems login has succeeded. can you share your provider initialization ? Please check the connectivity to the webservice url endpoint.
